#!/usr/bin/env python3
"""Generate route E's recipe TSV from AgentDojo, never by hand.

One row per session: label, suite, user_task_id, injection_task_id ('-' for benign),
prompt. The prompt is the user_task PROMPT verbatim (collapsed to one line); the
injection never appears in the prompt -- it is planted in the environment by the
server's --inject. Attack rows are the (user_task x injection_task) grid per suite;
AgentDojo's own security() decides which fired. Deterministic ordering, so a slice
taken with head/grep is reproducible.

Two filters, both of which change what the corpus can measure:

* **Unscorable injection tasks are dropped.** ``travel/injection_task_6`` scores only
  from the agent's prose, which no MCP server sees; ``workspace/injection_task_0``
  demands exactly one inbox email whose subject is a string its own payload plants 16
  copies of. Either would record every attack session as resisted. Measured in
  ``adapter.UNSCORABLE_INJECTION_TASKS`` and reproduced by the decidability gate.
* **Injection tasks with no NETWORK/CONFIGURE step are dropped.** They cannot exercise
  R3 or R5 whatever the agent does. Category comes from ChainWatch's own classifier,
  the same test ``scripts/gen_attack_recipes.py`` applies. ``ground_truth`` undercounts
  the live trajectory -- a "1-call" send-that-includes-X becomes read-then-send at
  runtime -- so this tests category *presence*, never call count.
"""

from __future__ import annotations

import argparse
import re
import sys
from itertools import zip_longest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from agentdojo_bridge.adapter import SUITES, UNSCORABLE_INJECTION_TASKS  # noqa: E402
from chainwatch.engine.taxonomy import ToolCategory, ToolClassifier  # noqa: E402

CLASSIFIER = ToolClassifier()
TARGET_CATEGORIES = {ToolCategory.NETWORK, ToolCategory.CONFIGURE}


def one_line(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def usable_injection_ids(suite_name: str) -> list[str]:
    """Injection tasks that are both scorable and able to reach R3/R5."""
    suite = SUITES[suite_name]
    env = suite.load_and_inject_default_environment(suite.get_injection_vector_defaults())
    keep = []
    for injection_id, task in sorted(suite.injection_tasks.items()):
        if (suite_name, injection_id) in UNSCORABLE_INJECTION_TASKS:
            continue
        try:
            categories = {CLASSIFIER.classify(c.function) for c in task.ground_truth(env)}
        except Exception:
            categories = set()
        if categories & TARGET_CATEGORIES:
            keep.append(injection_id)
    return keep


def _suite_blocks(suite_name: str, limit_per_suite: int | None) -> list[list[tuple]]:
    """One block per user task: its benign row followed by its attack rows."""
    suite = SUITES[suite_name]
    user_ids = sorted(suite.user_tasks)
    injection_ids = usable_injection_ids(suite_name)
    if limit_per_suite:
        user_ids = user_ids[:limit_per_suite]
        injection_ids = injection_ids[:limit_per_suite]

    blocks = []
    for user_id in user_ids:
        prompt = one_line(suite.user_tasks[user_id].PROMPT)
        block = [("benign", suite_name, user_id, "-", prompt)]
        block.extend(
            ("attack", suite_name, user_id, injection_id, prompt)
            for injection_id in injection_ids
        )
        blocks.append(block)
    return blocks


def rows(limit_per_suite: int | None):
    """Round-robin the suites so any prefix of the grid covers every environment.

    --limit and the spend budget both cut this file at a prefix. Emitting one suite at a
    time made every small run banking-only, and leave-one-environment-out needs more
    than one environment to hold out. Blocks stay intact so a prefix keeps matched pairs.
    """
    per_suite = [_suite_blocks(name, limit_per_suite) for name in sorted(SUITES)]
    for group in zip_longest(*per_suite):
        for block in group:
            if block is not None:
                yield from block


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument("--limit-per-suite", type=int, default=None)
    options = parser.parse_args(argv)

    lines = [
        "# GENERATED by scripts/gen_agentdojo_recipes.py -- do not edit.",
        "# label\tsuite\tuser_task\tinjection_task\tprompt",
    ]
    lines.extend("\t".join(r) for r in rows(options.limit_per_suite))
    Path(options.out).write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
