#!/usr/bin/env python3
"""Generate route F's recipe TSV from InjecAgent dev cases, never by hand.

One row per session: label, split, variant, case_index, user_tool, prompt. The prompt
is the case's published ``User Instruction`` verbatim (collapsed to one line) and is
identical across a case's benign and attack rows -- the injection lives in the tool
*response* the server serves, which is the whole design.

Row layout per dev case:

* one **benign** row at ``variant=base``. The clean response is the same template
  either way with the ``<Attacker Instruction>`` slot emptied, so a second benign row
  for ``enhanced`` would be a duplicate session wearing a different coordinate.
* one **attack** row per variant. ``base`` and ``enhanced`` are two published attack
  strengths and both are measured; they stay separable afterwards on the ``variant``
  column of the score sidecar.

``case_index`` addresses ``dev_cases(split, variant)`` positionally, so that function
must never reorder its output.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from injecagent_bridge.loader import SPLITS, dev_cases  # noqa: E402


def one_line(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def rows(limit: int | None):
    for split in SPLITS:
        cases = dev_cases(split, "base")
        if limit:
            cases = cases[:limit]
        for index, case in enumerate(cases):
            prompt = one_line(case["User Instruction"])
            user_tool = case["User Tool"]
            yield ("benign", split, "base", str(index), user_tool, prompt)
            for variant in ("base", "enhanced"):
                yield ("attack", split, variant, str(index), user_tool, prompt)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument("--limit", type=int, default=None)
    options = parser.parse_args(argv)

    lines = [
        "# GENERATED by scripts/gen_injecagent_recipes.py -- do not edit.",
        "# label\tsplit\tvariant\tcase_index\tuser_tool\tprompt",
    ]
    lines.extend("\t".join(r) for r in rows(options.limit))
    Path(options.out).write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
