#!/usr/bin/env python
"""Slice a GENERATED recipe TSV into disjoint shards, on whole fold groups.

Parallel capture is only safe if two processes never share a coordinate, and
`--resume` cannot supply that: it computes its skip set once at startup, so two
concurrent runs over overlapping rows both buy the same coordinate and
`assert_no_duplicates` then refuses every later run. Disjointness has to be a
property of the input files, and it has to be checked rather than intended --
which is also why this is a script rather than a shell one-liner: what a shard
file contains decides which coordinates were bought, so it belongs under the
same rule as the recipe files themselves.

Splitting on whole fold groups additionally keeps a benign task and its injected
twin inside one process, which is the grouping the task-level folds rely on.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable

#: The columns naming the published task, per route, keyed by row width.
#: AgentDojo: suite, user_task. InjecAgent: split, case_index -- which binds
#: `base` to `enhanced`, since the variant is not part of the task's identity.
GROUP_COLUMNS: dict[int, tuple[int, ...]] = {5: (1, 2), 6: (1, 3)}


def group_key(fields: list[str]) -> str:
    """The published task a row belongs to. Rows sharing it share a shard."""
    try:
        columns = GROUP_COLUMNS[len(fields)]
    except KeyError:
        raise ValueError(
            f"unrecognised recipe row of {len(fields)} columns; "
            f"expected one of {sorted(GROUP_COLUMNS)}"
        ) from None
    return ":".join(fields[index] for index in columns)


def shard(lines: Iterable[str], count: int) -> list[list[str]]:
    """Assign whole groups round-robin in first-seen order.

    Round-robin rather than by suite: banking carries seven injection tasks per
    user task where the others carry three, so slicing by suite leaves one shard
    twice the size of its siblings.
    """
    if count < 1:
        raise ValueError("shard count must be at least 1")
    buckets: list[list[str]] = [[] for _ in range(count)]
    assigned: dict[str, int] = {}
    for line in lines:
        if not line.strip() or line.startswith("#"):
            continue
        key = group_key(line.rstrip("\n").split("\t"))
        if key not in assigned:
            assigned[key] = len(assigned) % count
        buckets[assigned[key]].append(line)
    return buckets


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="shard_recipes.py")
    parser.add_argument("recipes", type=Path)
    parser.add_argument("--shards", type=int, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    options = parser.parse_args(argv)

    if not options.recipes.is_file():
        parser.error(f"recipe file does not exist: {options.recipes}")

    lines = options.recipes.read_text(encoding="utf-8").splitlines(keepends=True)
    data = [line for line in lines if line.strip() and not line.startswith("#")]
    try:
        buckets = shard(lines, options.shards)
    except ValueError as error:
        parser.error(str(error))

    # Checked, not intended: a slicer that silently dropped or duplicated a row
    # would buy the wrong corpus and say nothing.
    rejoined = sorted(row for bucket in buckets for row in bucket)
    if rejoined != sorted(data):
        print("shards do not reassemble the input; refusing to write", file=sys.stderr)
        return 2

    options.out_dir.mkdir(parents=True, exist_ok=True)
    header = f"# GENERATED by shard_recipes.py from {options.recipes.name} -- do not edit.\n"
    for index, bucket in enumerate(buckets):
        target = options.out_dir / f"{options.recipes.stem}_shard{index}.tsv"
        target.write_text(header + "".join(bucket), encoding="utf-8")
        groups = {group_key(row.rstrip("\n").split("\t")) for row in bucket}
        print(f"{target} rows={len(bucket)} groups={len(groups)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
